export const products = [
  {
    productImage: "brown2.jpg",
    quantity: 1,
    price: 30000,
    productName: "Eghonghon",
    instock: true,
    productId: 1,
  },
  {
    productImage: "DSC_8085.jpg",
    quantity: 1,
    price: 20000,
    productName: "Ofure",
    instock: true,
    productId: 2,
  },
  {
    productImage: "DSC_8070.jpg",
    quantity: 1,
    price: 25000,
    productName: "Ese",
    instock: true,
    productId: 3,
  },
  {
    productImage: "whiteflip.jpg",
    quantity: 1,
    price: 20000,
    productName: "Itohan",
    instock: true,
    productId: 4,
  },
  {
    productImage: "purpleleather.jpg",
    quantity: 1,
    price: 30000,
    productName: "Ovie",
    instock: true,
    productId: 5,
  },
  {
    productImage: "Josittingdown.jpg",
    quantity: 1,
    price: 35000,
    productName: "Ikhiene",
    instock: true,
    productId: 6,
  },
  {
    productImage: "pexelslides.jpg",
    quantity: 1,
    price: 25000,
    productName: "NohNoh",
    instock: true,
    productId: 7,
  },
];
